### ISSUE TITLE
Axum example not working

### ISSUE THREAD

**Issue by joloppo** [kurtbuilds/oasgen#13]
The axum examples seems completely broken. Even when fixing imports.

**Comment by kurtbuilds** [comment]
Thank you for flagging that.

There were a few issues with the README example, so I updated it and updated the dependency list.

Right now, it's still building off axum 0.6, so if you're running into a lot of compile issues, that's probably the reason.

I haven't investigated how easy it will be to update to 0.7, but the issue that was originally soft-blocking it have since been resolved. If you investigate this or even submit a PR, that contribution would be welcome. I'll close this issue, as the Axum example in the README should now compile under 0.6, but feel free to update here or a new thread if you care to explore the update to 0.7.

**Comment by kurtbuilds** [comment]
Quick update: the upgrade path was fairly straight forward, and just published a new version with axum = 0.7 and http = 1.0.

**Comment by joloppo** [comment]
Ooh awesome, I'll give it a try later.
